### ISSUE TITLE
Image

### ISSUE THREAD

**Issue by JeremyV33** [JeremyV33/LinuxPROJECT#2]
Répertoire d'image

**Comment by JeremyV33** [comment]
[Linux-SujetProposé.pdf](https://github.com/JeremyV33/LinuxPROJECT/files/4142415/Linux-SujetPropose.pdf)

**Comment by JeremyV33** [comment]
[Infra Linux.pdf](https://github.com/JeremyV33/LinuxPROJECT/files/4142416/Infra.Linux.pdf)

**Comment by JeremyV33** [comment]
![image](https://user-images.githubusercontent.com/58468543/73590526-b7caaf00-44e3-11ea-8d55-fa1d940cfb94.png)

**Comment by JeremyV33** [comment]
![image](https://user-images.githubusercontent.com/58468543/73590832-73411280-44e7-11ea-9e11-5673e481e58d.png)

**Comment by JeremyV33** [comment]
![image](https://user-images.githubusercontent.com/58468543/73590935-d0899380-44e8-11ea-92b9-28855a27d0cd.png)

**Comment by JeremyV33** [comment]
![image](https://user-images.githubusercontent.com/58468543/73642897-d7dca880-4672-11ea-8118-38c315dfee4c.png)

**Comment by JeremyV33** [comment]
![image](https://user-images.githubusercontent.com/58468543/73642909-dc08c600-4672-11ea-8498-16022cd49125.png)

**Comment by JeremyV33** [comment]
![image](https://user-images.githubusercontent.com/58468543/73642918-df03b680-4672-11ea-9f0a-3ffca14bbfb9.png)

**Comment by JeremyV33** [comment]
![image](https://user-images.githubusercontent.com/58468543/73642926-e32fd400-4672-11ea-8019-864b703ae1bc.png)

**Comment by JeremyV33** [comment]
![image](https://user-images.githubusercontent.com/58468543/73642934-e6c35b00-4672-11ea-98ad-1c9caaf41850.png)

**Comment by JeremyV33** [comment]
![image](https://user-images.githubusercontent.com/58468543/73642944-e925b500-4672-11ea-87ca-2515dc61da97.png)

**Comment by JeremyV33** [comment]
![image](https://user-images.githubusercontent.com/58468543/73642947-eb880f00-4672-11ea-8cd3-e8cff1cbb1b7.png)

**Comment by JeremyV33** [comment]
![image](https://user-images.githubusercontent.com/58468543/73642958-efb42c80-4672-11ea-9e76-e1007f9830c9.png)

**Comment by JeremyV33** [comment]
![image](https://user-images.githubusercontent.com/58468543/73642963-f2af1d00-4672-11ea-89fb-f1e540b26b66.png)

**Comment by JeremyV33** [comment]
![image](https://user-images.githubusercontent.com/58468543/73642979-f773d100-4672-11ea-80a8-5e59f5ba66c0.png)

**Comment by JeremyV33** [comment]
![image](https://user-images.githubusercontent.com/58468543/73642986-fd69b200-4672-11ea-986b-0929b0897f07.png)

**Comment by JeremyV33** [comment]
![image](https://user-images.githubusercontent.com/58468543/73643000-00fd3900-4673-11ea-9555-ef9b9284b8f6.png)

**Comment by JeremyV33** [comment]
![image](https://user-images.githubusercontent.com/58468543/73643009-035f9300-4673-11ea-8046-32d6ad918534.png)

**Comment by JeremyV33** [comment]
![image](https://user-images.githubusercontent.com/58468543/73643021-08bcdd80-4673-11ea-89ea-789565c4300a.png)

**Comment by Pidartois** [comment]
![image](https://user-images.githubusercontent.com/51946423/73828583-d392c580-4801-11ea-8420-2149d3d45a6b.png)

**Comment by JeremyV33** [comment]
![image](https://user-images.githubusercontent.com/58468543/73833440-499b2a80-480a-11ea-927a-6dd8197bfec4.png)

**Comment by JeremyV33** [comment]
![image](https://user-images.githubusercontent.com/58468543/73833805-df36ba00-480a-11ea-88d9-88b021eef0c8.png)
